### ISSUE TITLE
아..

### ISSUE THREAD

**Issue by ghost** [Thestars3/arkzip#3]
데탑이 생겼는데 (듀얼코어요) 놋북보다 몇배 빠르지만 치명적인게 32비트네요 ㅋ
필수 패키지인 arkzip 을 설치할 방도가 혹시 없을까욘 T.T

**Comment by tb69wn6127** [comment]
arkzip의 핵심은 arklibrary인데, 제가 만든 프로그램에서 쓰이는게 64비트용입니다.
이 라이브러리를 32비트용으로 교체하시고, 64비트 환경에 의존적인 부분을 조금 수정해주시면 됩니다.
아마, 라이브러리만 교체하면, 바로 빌드해서 쓸수 있으실 겁니다.
