### ISSUE TITLE
Raspbian 지원

### ISSUE THREAD

**Issue by g6123** [Thestars3/arkzip#4]
Raspberry Pi에서 Raspbian을 돌리고 있는데요,
가볍게 cli에서만 쓸 수 있도록 설치할 방법은 혹시 없을까요?

**Comment by tb69wn6127** [comment]
GUI용으로 만들어진 부분을 제거한뒤 빌드하시면 됩니다.
arkgui.pro가 소속된 폴더를 제거.
arkzip/arkzip/arkzip.pro에서 arkgui 서브디렉토리 제거.
arkzip/option.cpp의 void Option::process() 메소드에서 arkgui를 호출하는 부분과 옵션처리 부분을 제거
arkzip/option.hpp에서 arkgui 프로그램 경로 설정 변수를 제거.
arkzip/common.pro에서 arkgui 프로그램 경로 제거.

arkzip 자체의 크기는 작은데, 의존하는 qt 프레임워크가 무겁습니다. 크기 문제를 해결하려면, 위의 방법만으로 해결 할 수 없습니다. 해결하시려면, qt 프레임워크를  설치할때, 수동으로 빌드하면서 gui나 기타 옵션을 빼고 설치하셔야 합니다.

**Comment by g6123** [comment]
네, 고맙습니다. 기회가 된다면 해 보고 이 이슈에 내용을 추가해 보겠습니다..

**Comment by tb69wn6127** [comment]
어떻게 사용하려는건지 모르겠지만, 라즈베리파이에서 사용한다면 python에서 ctype으로 불러와서 쓰는것도 좋습니다. arkzip은 arklibrary에 인코딩 분석, 예외처리, 추가 확장자 지원, 중복제거, 로그 작성 등의 부가기능을 붙여 만들어 졌습니다. 압축해제 자체만 수행하려 한다면 arklibrary를 ctype으로 불러와서 사용 할 수 있습니다.
arkgui를 제거하고, qt프레임워크를 수동으로 빌드하는것 보다 나을겁니다.
